layout_spectrum: 0.6183759386267623
typography_spectrum: 0.8007089531362648
color:
  brandStrength: 0.1250640235595073
  lightness: 0.8186049776441316
  saturation: 0.9298643428484661
  rhythmicContrast: 0.20828143648139322
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: macbookpro.ist
content: []
title: long live the macbook pro
description: and all things tech-related
url: 'https://macbookpro.ist'
purpose:
  - type: internal
    label: Father's Day DEALS
    item: 2f2b8bde-859e-49f6-8f5e-ee84cfdf732f
analytics:
  google: UA-101080960-1
  twitter: 'https://twitter.com/ugivme'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d913002b-a8c5-4d18-9de5-d398c61695da.png
